[CREATURE]  
infinite_energy = false
speed_factor = 20
colour = [255, 255, 255]
low_energy_limit = 20
health_energy_reduction = 1.4
energy_min = 50
energy_max = 150
health_min = 60
health_max = 100
mass_min = 50
mass_max = 90

[ENV]
loop_delay = 100
creature_count = 200
background = [0, 0, 0]
scr_width = 1200
scr_height = 900

